-- SCREEN RESOLUTION
WIDTH = 1280
HEIGHT = 720
VIRTUAL_WIDTH = 432
VIRTUAL_HEIGHT = 243

-- PADDLE DIMENSIONS/PROPERTIES
PLAYER1X = 5
PLAYER2X = VIRTUAL_WIDTH-10
PLAYER1Y = 30
PLAYER2Y = VIRTUAL_HEIGHT-30

PADDLE_HEIGHT = 20
PADDLE_WIDTH = 5

PADDLE_SPEED = 200

-- BALL DIMENSIONS/PROPERTIES
BALL_WIDTH = 4
BALL_HEIGHT = 4
BALL_X = VIRTUAL_WIDTH/2 - BALL_WIDTH/2
BALL_Y = VIRTUAL_HEIGHT/2 - BALL_HEIGHT/2

-- first player to reach this score will win the game
WINNING_SCORE = 2